# -*- coding: utf-8 -*-
"""GA_OSSP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JpBuGeJh6CXaUPRPqRgpxdCUunRywLfF

# Solving the open shop scheduling problem with Genetic Algorithms
"""


from copy import copy

import matplotlib.pyplot as plt
import array
import random
import numpy as np
from deap import algorithms, base, creator, tools

from problem.ossp_problem import OsspProblem

"""### OSSP 
This eq is related to the maximum completion time of all jobs that must be processed on machines.
On the other hand, it indicates that the total processing time
of jobs must at least be equal to their defined required time
to process their operations. The second part shows the maximum completion time of jobs assigned to a given machine.
Therefore, the processing time of each machine must at
least be equal to the sum of all times required for operating its assigned jobs. The optimal makespan of an open-shop
scheduling is never less than L, but it does not indicate that
it should be necessarily equal to L
"""

# Variables globales

# # 3 X 3 Problem
MATRIX = [[1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 1, 1, 2, 2, 2, 3, 3, 3],
          [3, 1, 2, 1, 3, 2, 1, 2, 3],
          [2, 3, 5, 5, 7, 1, 4, 5, 1]]

ossp = OsspProblem(MATRIX,3)

"""OSSP"""


def setup_ga_ossp( indpb = 0.2):
    creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
    creator.create("Individual", list, fitness=creator.FitnessMin)
    toolbox = base.Toolbox()
    toolbox.register("indices", random.sample, range(1,10), 9)
    toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.indices)
    toolbox.register("population", tools.initRepeat, list, toolbox.individual)
    toolbox.register("evaluate", ossp.evaluate)
    toolbox.register("mate", tools.cxTwoPoint)
    toolbox.register("mutate", tools.mutFlipBit, indpb=indpb)
    toolbox.register("select", tools.selTournament, tournsize=2)
    return toolbox


def run_ga_ossp(toolbox, population_size=92, cxpb=0.85, mutpb=0.1):
    pop = toolbox.population(n=population_size)
    # only save the very best one
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)
    stats.register("max", np.max)
    algorithms.eaSimple(pop, toolbox, cxpb=cxpb, mutpb=mutpb, ngen=250, stats=stats, halloffame=hof)
    return pop, stats, hof

'''
plt.plot(x, y, 'o', color='black')
toolbox = setup_ga_ossp(mate = tools.cxOrdered, indpb = 0.05)
pop, stats, hof = run_ga_ossp(toolbox, population_size = 100, cxpb = 0.85, mutpb = 0.25)
ind = hof[0]
print("Solution: ", ind)
plt.figure(2)
full_tour = copy(ind)
full_tour.append(ind[0])

plt.plot(x[full_tour], y[full_tour])
'''

if __name__ == '__main__':
    toolbox=setup_ga_ossp()
   # print(toolbox.population)
    run_ga_ossp(toolbox)